spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**
          filters:
            - name: JwtAuthenticationFilter
  application:
    name: API-Gateway
  boot:
    debug: true

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway.nodeValue: TRACE
    org.springframework.boot: DEBUG
    com.netflix.discovery: DEBUG
    root: INFO

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true

server:
  port: 8085