server:
  port: 8085
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        # Route for User Service
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user/**,/group/**
          filters:
            - name: JwtAuthenticationFilter
        # Route for Expense Service
        - id: EXPENSE-SERVICE
          uri: lb://EXPENSE-SERVICE
          predicates:
            - Path=/expense/**,/balance/**,/comments/**,/settlement/**
          filters:
            - name: JwtAuthenticationFilter
        # Route for Orchestrate Service
        - id: ORCHESTRATE-SERVICE
          uri: lb://ORCHESTRATE-SERVICE
          predicates:
            - Path=/activity/**,/invite/**
          filters:
            - name: JwtAuthenticationFilter
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
            allowedHeaders:
              - content-type
  application:
    name: API-Gateway
  boot:
    debug: true

logging:
  level:
    org.springframework.cloud.netflix.eureka: DEBUG
    org.springframework.cloud.gateway.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway.nodeValue: TRACE
    org.springframework.boot: DEBUG
    com.netflix.discovery: DEBUG
    root: INFO

eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
